### ISSUE TITLE
suggestion for features...

### ISSUE THREAD

**Issue by jklymak** [QuLogic/scipy2020-mpl-update#1]
https://github.com/QuLogic/scipy2020-mpl-update/blob/1767725b1fd0b93c6baa183b5ec2d1276ec1984c/feature33.py#L128

Suggest the colorbar *not* extend under the lhs histogram, because it doesn't pertain to the histogram. I'd also shrink it a bit (`shrink=0.8`)

Otherwise, looks great.  Crazy that you did this in MPL!

**Comment by QuLogic** [comment]
The reason for that is that the histogram Axes will not be shrunk by the colorbar, so it won't line up with the main Axes.

I know `constrained_layout=True` would fix that in general, but when I tried it here, it resized all the mosaic Axes to fit the whole Figure, which is not wanted. Am I missing something in the `subplot_mosaic` call, or is there a missing feature/bug there?

**Comment by QuLogic** [comment]
And by tried `constrained_layout=True`, I mean:
```patch
diff --git a/feature33.py b/feature33.py
index 1ba71d4..09f32d7 100644
--- a/feature33.py
+++ b/feature33.py
@@ -108,7 +108,7 @@ def sharing():
     Create slide for feature highlight of post-hox Axes sharing.
     """
 
-    fig = new_slide()
+    fig = new_slide(constrained_layout=True)
 
     slide_heading(fig, '3.3 Feature: post-hoc Axes sharing')
 
@@ -128,7 +128,8 @@ axd['histy'].sharey(axd['scat'])""", **CODE)
                                               'top': 0.65})
 
         im = axd['scat'].scatter(x, y, c=c, cmap='RdBu', picker=True)
-        fig.colorbar(im, ax=[axd['scat'], axd['histy']],
+        fig.colorbar(im, ax=axd['scat'],
+                     shrink=0.8,
                      orientation='horizontal')
 
         _, _, patchesx = axd['histx'].hist(x)
diff --git a/mplslide.py b/mplslide.py
index 4d97cea..57f9321 100644
--- a/mplslide.py
+++ b/mplslide.py
@@ -60,7 +60,7 @@ def check_requirements():
         sys.exit('Calibri or Carlito font must be installed.')
 
 
-def new_slide(plain=False):
+def new_slide(plain=False, **kwargs):
     """
     Create a new slide.
 
@@ -70,7 +70,7 @@ def new_slide(plain=False):
         Whether to leave out any slide decorations (e.g., logo).
     """
 
-    fig = plt.figure(figsize=FIGSIZE, dpi=DPI)
+    fig = plt.figure(figsize=FIGSIZE, dpi=DPI, **kwargs)
     fig.mplslide_props = {'plain': plain}
     return fig
 
```

**Comment by jklymak** [comment]
Ah, I see

The "right" way to do this and still use `constrained_layout` is to nest the mosaic inside a subgridspec.  This will all be easier when we have "sub panels" https://github.com/matplotlib/matplotlib/pull/17437
